# poetry self add poetry-bumpversion

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool]
[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.mypy]
pretty = true
python_version = "3.9"
show_error_codes = true
strict = true

[tool.ruff]
select = ["ALL"]
ignore = []

[tool.ruff.mccabe]
max-complexity = 18

[tool.poetry]
authors = ["eggplants <w10776e8w@yahoo.co.jp>"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only"
]
description = "My Best Python Project"
keywords = ["sample-project"]
name = "my_best_python_project"
packages = [{include = "my_best_python_project"}]
license = "MIT"
readme = "README.md"
repository = "https://github.com/eggplants/my-best-python-project"
version = "0.0.5"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"

[tool.poetry.group.dev.dependencies]
mypy = "^1.0.0"
pre-commit = "^2.20.0"
taskipy = "^1.10.3"

[tool.poetry.scripts]
mbpp = "my_best_python_project.main:main"

[tool.poetry_bumpversion.file."my_best_python_project/__init__.py"]

[tool.taskipy.tasks]
lint = "pre-commit run -a"
profile = "python -m cProfile"
