name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.12'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
        python-version: ${{ matrix.python-version }}
    - run: uv sync --all-extras --dev
    - run: uv run task test:ci
    - uses: qltysh/qlty-action/coverage@4ce0ba739c2c357fa9ef5c8273974e9b1e30d067
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: ${{github.workspace}}/cov.xml
